### ISSUE TITLE
Deprecated function fs.existsSync(path)

### ISSUE THREAD

**Issue by noopurj** [anvaka/ngraph.offline.layout#2]
Hello, 
I cannot use ngraph.offline.layout using npm because the function fs.existsSync(path) used in index.js is deprecated.

**Comment by anvaka** [comment]
Oops, this has slipped under my radar.  

Can you elaborate what is not working? According to node docs [existsSync()](https://nodejs.org/api/fs.html#fs_fs_existssync_path) is not deprecated in the latest version of node (v7.10.0)

**Comment by anvaka** [comment]
Closing, as there is no response. Please re-open when you have time to provide more details
