### ISSUE TITLE
'Value is out of bounds' when writing int.

### ISSUE THREAD

**Issue by theepicsnail** [anvaka/ngraph.offline.layout#3]
The positions generated by forcelayout3d are almost surely not going to be ints.

This causes the call to writeInt32LE to throw an exception
https://github.com/anvaka/ngraph.offline.layout/blob/master/index.js#L103

I'm not sure about other use cases, but for mine adding "|0" to truncate each dimensions value is fine.

Alternatively writeFloatLE/writeDoubleLE, but your docs say 'int' specifically so I don't know if that's relied upon somewhere.

**Comment by anvaka** [comment]
Other applications expect this to be integer. What version of node are you using? I tried this in `v6.3.0`

``` js
const buffer = Buffer.allocUnsafe(4);
buffer.writeInt32LE(2.5, 0)
console.log(buffer); // prints <Buffer 02 00 00 00>
```

Don't see an exception. I wonder what could be causing it your case...

**Comment by theepicsnail** [comment]
Ah, that's fair. I hadn't checked, this machine has version 0.10.25 which is impressively bad. I've updated to 7.2.0 and it's working just fine.

**Comment by anvaka** [comment]
I'm glad it worked!
