### ISSUE TITLE
Offline layout diverges from ngraph.pixel online layout

### ISSUE THREAD

**Issue by mlippautz** [anvaka/ngraph.offline.layout#5]
Hej,

I am prototyping a visualization for 100k+ nodes. Not sure I will actually get there but this is another problem.

I am trying to use the offline layout to avoid layout computations while using ngraph.pixel. However, I see different results in layouting. When using ngraph.pixel the graph nicely expands after a few iterations; ngraph.offline only generates a blob of nodes, even after ~20k iterations. Both strategies use ngraph.forcelayout3d for the layout computation.

I've verified that the positions I load (ArrayBuffer -> Int32Array) correspond to the positions computed using the offline layout. 

Are there any adjustments to the physics engine necessary? I am loading the positions after setting `renderer.isStable(true)` using `graph.forEachNode()`.

**Comment by anvaka** [comment]
Hi Michael,

There are a few things that influence final layout: 

1. The physics settings.
2. The graph structure.
3. Initial positions of nodes.

By default, both `ngraph.pixel` and `ngraph.offline.layout` use exactly the same settings. No adjustment is required, unless you are rendering different graphs. If graphs are the same, I'd double check the `settings` object (set breakpoint in the [step function](https://github.com/anvaka/ngraph.physics.simulator/blob/master/index.js#L96))

Are you rendering the same graph? 

If your graph is public - feel free to share it, and I'll take deeper look into what might be causing it. 100k nodes should be easy to render by this library.

**Comment by mlippautz** [comment]
Thanks for the fast reply. I should've added that I am also using the `dot()` converter to obtain the graph. I am using something along the lines below. 

**Offline layouting:**
```js
var createGraph = require('ngraph.graph');
var dot = require('ngraph.fromdot');
var graph = dot(DATA_FROM_FILE);
var createLayout = require('ngraph.offline.layout');
var layout = createLayout(graph, {
  iterations: 1000, 
  saveEach: 50,
  layout: require('ngraph.forcelayout3d') 
});
layout.run();
```
**Rendering:**
```js
var createGraph = require('ngraph.graph');
var dot = require('ngraph.fromdot');
var graph = dot(DATA_FROM_FILE);
var renderGraph = require('ngraph.pixel');
var renderer = renderGraph(g);
var layout = renderer.layout()
renderer.stable(true);
graph.forEachNode(function (nodeModel) {
  var x = POS[nodecnt+0];
  var y = POS[nodecnt+1];
  var z = POS[nodecnt+2];
  layout.setNodePosition(nodeModel.id, x, y, z);
  nodecnt+=3;
});
```

The attached [graph.txt](https://github.com/anvaka/ngraph.offline.layout/files/1002199/graph.txt) is heavily reduced. I just wanted to get the offline workflow up and running.

**Comment by anvaka** [comment]
Here is what I'm getting: https://anvaka.github.io/ngraph.pixel/demo/offline/index.html 

I see that there are couple nodes that are connected to most of other nodes (`N_0x7f3141c8110` is connected to ~39% of the graph, and `N_0x3cba7e8f1688` is connected to 14% of the graph). 

Is this layout the same as what you have? Did you expect it to look differently?

PS: Here is the code for the demo: https://github.com/anvaka/ngraph.pixel/tree/master/demo/offline

**Comment by mlippautz** [comment]
I am getting the same layout when rendering offline. However, the one during online rendering differs completely. 

Thanks for investigating!

**Comment by anvaka** [comment]
Ah, I see what's going on.

The positions are indeed the same in two layouts. The `ngraph.pixel` thought that layout was stable, and never notified webgl code that its array buffers were modified and need to be re-rendered.

I added a new method `redraw()` on the renderer, that fixes the error. Just call it once you've got your positions initialized.

Here is [an example].(https://github.com/anvaka/ngraph.pixel/blob/5634f8b66d6257a1731be546a2726d8aedeae086/demo/offline/index.js#L53)

The graph looks better now: https://anvaka.github.io/ngraph.pixel/demo/offline/index.html

**Comment by mlippautz** [comment]
Awesome, thanks a lot! That solved the issue for me.
